### ISSUE TITLE
Missing tests for the MAC command

### ISSUE THREAD

**Issue by macpijan** [Dasharo/dcu#12]
New command was added (https://github.com/Dasharo/dcu/pull/10), but no new tests have been added. This should not happen @BeataZdunczyk @mkopec

**Comment by philipandag** [comment]
The following test cases for the mac command were added in https://github.com/Dasharo/dcu/pull/13:
- Set valid MAC
- Set invalid MAC
- Get MAC
- Get MAC Bad checksums
- Set MAC Bad checksums
- MAC Unsupported binary
